name = "tryout"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-21"

kv_namespaces = [ 
         { binding = "MY_KV", id = "f525a3885aae4454b4a03534c01d40a8" }
]